# -*- coding: utf-8 -*-
"""Task 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hWVUbhadTg5FaZlIJ26gUv_IFez5jyuS
"""

import pandas as pd



df=pd.read_csv('/content/Mall_Customers.csv')
df.info()

df.shape

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.displot(df.Age)

plt.pie(df.Age.value_counts())
plt.title('Age')
plt.show()

sns.lineplot(x = df.Age,y=df.Gender)

sns.scatterplot(x = df.Age,y=df.Gender)

sns.pairplot(df)

sns.heatmap(df.corr(),annot=True)

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df.Gender = le.fit_transform(df.Gender)

df.head()

X = df.iloc[:,:-1]
X.head()

X.tail()

y =df.Age
y.head()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 47)

y_train.shape

y_test.shape

y_train.value_counts()

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()

model.fit(x_train,y_train)

y_pred = model.predict(x_test)

y_pred_train = model.predict(x_train)

from sklearn.metrics import accuracy_score,classification_report

accuracy_score(y_test,y_pred)

accuracy_score(y_train,y_pred_train)

pd.crosstab(y_test,y_pred)

print(classification_report(y_test,y_pred))

